import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import Button from "@/components/Button";
import { useRouter } from "next/router";
import styles from "../styles/Home.module.css";
import { FaShoppingCart } from "react-icons/fa";

export default function Home() {
  const router = useRouter();
  const handleClick: React.MouseEventHandler<HTMLButtonElement> = () => {
    console.log("Button clicked!");
    router.push("/books");
  };

  return (
    <>
      <Head>
        <title>Books App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.headerContainer}>
        </div>

        <div className={styles.header}>
          <div className={styles.headerText}>
            <h4>Hundreds of books</h4>
            <h3>picked for you</h3>
          </div>
        </div>
        <button className={styles.addbtn} onClick={handleClick}>
          <FaShoppingCart />
        </button>
       
        <div className={styles.section2}>
          <img
            src="http://localhost:3000/book1.jpg"
            alt="book2"
            className={styles.img}
          />

          <div className={styles.textsectionHome2}>
            <h1 className={styles.textTitle}>
              Discover our vast collection of books
            </h1>
            <button className={styles.btn} onClick={handleClick}>
              Go to shop
            </button>
          </div>
        </div>
      </main>
    </>
  );
}
